### Get Orders
GET http://localhost:42527/odata/v4/manage-orders/GetOrders

### Get Orders
GET http://localhost:42527/odata/v4/manage-orders/GetOrders('client1@client1.com')

### Create Order
POST  http://localhost:42527/odata/v4/manage-orders/CreateOrders HTTP/1.1
Content-Type: application/json

{
    "ClientEmail": "jch127518.com",
    "FirstName": "George",
    "LastName": "Contreras",
    "CreatedOn" : "2000-04-28"
}